import { Archive, LayoutDashboard, Plus, Star } from 'lucide-react';
import { BoardSummary, User, Workspace } from '../types';
import UserMenu from './UserMenu';

type Props = { user: User | null; workspaces: Workspace[]; boards: BoardSummary[]; active: string; activeWorkspaceId?: number; onWorkspace: (workspace: Workspace) => void; onCreateWorkspace: () => void; onCreateBoard: () => void };

export default function Sidebar({ user, workspaces, boards, active, activeWorkspaceId, onWorkspace, onCreateWorkspace, onCreateBoard }: Props) {
  const selectedWorkspaceId = activeWorkspaceId ?? (Number(localStorage.getItem('teamflow_active_workspace')) || undefined);
  const item = (href: string, label: string, Icon: typeof LayoutDashboard) => <a href={href} className={`sidebar-item flex items-center gap-3 rounded-lg px-3 py-2.5 transition-colors ${active === href ? 'bg-violet-600/10 text-violet-400' : 'text-zinc-400 hover:bg-zinc-800 hover:text-zinc-100'}`}><Icon className="h-5 w-5"/>{label}</a>;
  return <aside className="fixed bottom-0 left-0 top-16 z-40 hidden w-[280px] flex-col border-r border-zinc-800 bg-zinc-900 lg:flex"><nav className="space-y-1 p-4">{item('/dashboard/','Мои доски', LayoutDashboard)}{item('/favorites/','Избранное', Star)}{item('/archive/','Архив', Archive)}</nav><div className="px-4 py-3"><div className="mb-2 flex items-center justify-between"><h3 className="text-xs font-semibold uppercase tracking-wider text-zinc-500">Рабочие пространства</h3><button onClick={onCreateWorkspace} className="rounded-lg p-1.5 text-violet-400 hover:bg-violet-600/10 hover:text-violet-300" title="Добавить пространство"><Plus className="h-4 w-4"/></button></div><div className="space-y-1">{workspaces.map((workspace) => <button key={workspace.id} onClick={() => { localStorage.setItem('teamflow_active_workspace', String(workspace.id)); onWorkspace(workspace); }} className={`workspace-btn flex w-full items-center gap-3 rounded-lg px-3 py-2 text-left text-sm transition-colors ${selectedWorkspaceId === workspace.id ? 'bg-violet-600/15 text-violet-300' : 'text-zinc-400 hover:bg-zinc-800 hover:text-zinc-100'}`}><span className={`flex h-5 w-5 shrink-0 items-center justify-center rounded text-xs font-semibold text-white ${selectedWorkspaceId === workspace.id ? 'bg-violet-600' : 'bg-zinc-700'}`}>{workspace.name.charAt(0).toUpperCase()}</span><span className="truncate">{workspace.name}</span></button>)}</div></div><div className="flex-1 overflow-y-auto px-4 py-2"><h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-500">Доступные доски</h3><div className="space-y-1">{boards.map((board) => <a key={board.id} href={`/board/${board.id}/`} className="flex items-center gap-2 rounded-lg px-3 py-2 text-sm text-zinc-400 transition-colors hover:bg-zinc-800 hover:text-zinc-100"><span className="h-2 w-2 shrink-0 rounded-full" style={{ backgroundColor: board.color || '#8b5cf6' }}/><span className="min-w-0 flex-1 truncate">{board.title}</span>{board.is_shared && <span className="shrink-0 rounded bg-blue-500/15 px-1.5 py-0.5 text-[10px] font-medium text-blue-300">команда</span>}</a>)}</div></div><div className="border-t border-zinc-800 p-4"><UserMenu user={user} fullWidth placement="up"/><button onClick={onCreateBoard} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-zinc-800 px-4 py-2.5 text-sm text-zinc-300 transition-colors hover:bg-zinc-700"><Plus className="h-4 w-4"/>Создать доску</button></div></aside>;
}
